### ISSUE TITLE
make clean should remove "bitmonero" directory

### ISSUE THREAD

**Issue by mbg033** [mbg033/monero-core#22]

**Comment by needmoney90** [comment]
Are the wallet files currently stored in the same directory as simplewallet (as is default in bitmonero), or do we have a dedicated wallet directory now (either in ~ or in the monero-core dir)? If so, this could be slightly dangerous, and carry the risk of deleting someone's wallet. I'm sure you're already taking this into account, just curious.

**Comment by mbg033** [comment]
Wallet files are stored in "%USERPROFILE%\Documents\Monero Accounts" (Windows) and "$HOME/Monero Accounts" (OSX and Linux). "bitmonero" directory is just a build-time dependency here inside source tree
