### ISSUE TITLE
project file: update/compile translation files automatically with make

### ISSUE THREAD

**Issue by mbg033** [mbg033/monero-core#23]

**Comment by skironDotNet** [comment]
Let me know if I can participate in translation to Polish.
Great work btw.

**Comment by skironDotNet** [comment]
Let me know if I can participate in translation to Polish.
Great work btw.

**Comment by mbg033** [comment]
Thanks, that would be helpful. Just added Polish translation file

**Comment by mbg033** [comment]
Sorry, closed issue before replied

**Comment by skironDotNet** [comment]
Should I get the permission to commit to master or get a brunch or should I fork and then you'll merge of fork?

**Comment by mbg033** [comment]
Please fork, create pull request and I'll merge

**Comment by skironDotNet** [comment]
Because some of the translations are UI context dependable I may initially provide not quite exact translations. Once I'll figure out how to compile it on Windows I'll be able to apply revisions by looking at the UI.

**Comment by mbg033** [comment]
I'll try to complete "Compiling" section soon, but in general, it supposed to be built with MSYS2 environment, mostly because of bitmonero (libwallet_merged) dependency. Probably Qt packaged by qt.io (mingw version) can be used to build and link the app, but libwallet_merged lib still needs to be built under MSYS2 and it also depends on boost, so it seems MSYS2 is an easier option. I do the development under Linux, switching to Windows to check the build periodically.

"get_libwallet_api.sh" is the helper script that builds libwallet dependency.
