### ISSUE TITLE
Amount Field in Transfer Tab needs validation

### ISSUE THREAD

**Issue by medusadigital** [mbg033/monero-core#38]
I think the Amount Field in Transfer Tab needs some validation.
## Situation right now:
- Amount gets not always validated against balance.

With low mixing Count it seems to work: 

![notenoughmoney](https://cloud.githubusercontent.com/assets/17108301/17635069/cb06e782-60d5-11e6-87d0-fb5acacc4e8b.jpg)

But with High mixing count it reacts differently and tries to look for outputs to mix before validation against acount balance: 

![notenoughmoney_highmix](https://cloud.githubusercontent.com/assets/17108301/17635086/e5cc49cc-60d5-11e6-959c-d1a6f784369d.jpg)
- If Field Amount is empty, Send Button works but nothing happens (same like Address Field) ---> OK
- If Field Amount has invalid value, value gets replaced by dummy value.
  ![amount1](https://cloud.githubusercontent.com/assets/17108301/17633348/28549596-60cd-11e6-8b6a-00ee5727e6b0.jpg)
  ![amount2](https://cloud.githubusercontent.com/assets/17108301/17633352/2b51edf2-60cd-11e6-9d7a-31e2aed3982d.jpg)
## How it should be:
- Amount should always be validated correctly against balance
- Field Amount should be validated correctly, if validation fails, Error message should be displayed.
  Message from Simplewallet is quite cool: 

>  expected number from 0 to 18446744.073709551615

**Comment by mbg033** [comment]
@medusadigital, please check 4fa8ad3b199483094cf9988f33da1ab6343d7c8a

**Comment by medusadigital** [comment]
works --> closed
