### ISSUE TITLE
Fatal Error when trying to build monero-core

### ISSUE THREAD

**Issue by phloatingman** [mbg033/monero-core#52]
I'm trying to follow the directions from here...

https://github.com/mbg033/monero-core

I'm running a fresh install of Ubuntu 16.04.1 x86 in VirtualBox.

When I get to "make" it gives me the following fatal error.

```
In file included from main.cpp:38:0:
src/libwalletqt/WalletManager.h:5:32: fatal error: wallet/wallet2_api.h: No such file or directory
compilation terminated.
Makefile:596: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

Can anyone point me in the right direction?

**Comment by radfish** [comment]
You need to manually merge monero-project/monero-core/PR # 14 in order to build (alternatively use `develop` branch in this repo), because monero daemon repo was updated to not build/install wallet lib/headers by default (need to pass `BUILD_GUI_DEPS=ON` option to cmake).

**Comment by phloatingman** [comment]
Thanks for the info...  It worked!  Here's what I did...

```
$ git clone -b develop https://github.com/mbg033/monero-core
$ cd monero-core
$ ./build.sh
```

And the resulting binary was in ~/monero-core/build/release/bin/monero-core
