### ISSUE TITLE
Recive Tab: Integrated Address wrong

### ISSUE THREAD

**Issue by medusadigital** [mbg033/monero-core#54]
Situation right now:

![recive](https://cloud.githubusercontent.com/assets/17108301/18450315/cd7de27a-7932-11e6-9b80-c4a3434f8191.png)

What i would expect:

![reciveist](https://cloud.githubusercontent.com/assets/17108301/18450334/dc2055c4-7932-11e6-9fed-8653930fa932.jpg)

**Comment by medusadigital** [comment]
my bad (http://pastebin.com/bp5RKXuC)

**Comment by luigi1111** [comment]
Yes the short payment ID is converted to base58 as part of the serialized address.
