### ISSUE TITLE
monero-core refresh window needs more information

### ISSUE THREAD

**Issue by medusadigital** [mbg033/monero-core#56]
As a user i want to see how the task of scanning the blockchain is processing. Therefore the same Information should be provided to the user as in monero CLI wallet, wich is the current Block Height.

i Imagine something like this:
![monero-core_height](https://cloud.githubusercontent.com/assets/17108301/18510408/185ef18e-7a7e-11e6-83ea-d27be469a22a.jpg)

probably low priority, but since recreation from seed takes a while, this would sure increase the overall user experience

**Comment by luigi1111** [comment]
Maybe a message in a corner saying "Wallet is synchronizing. This will take some time." with a completion % if you hover over it or something (and not locking up the rest of the functions while it is ongoing).

**Comment by medusadigital** [comment]
nice work @mbg033 

Screenshot for historical purpose: 

![xmrnewsyncpv](https://cloud.githubusercontent.com/assets/17108301/18930182/7e5f9a70-85c7-11e6-9a85-0a9dbd09711b.png)

**Comment by Jaqueeee** [comment]
Nice!
Works great on OS X / Macbook air.

**Comment by medusadigital** [comment]
implemented --> close
