### ISSUE TITLE
Gui crahes when history is open and money is spent

### ISSUE THREAD

**Issue by medusadigital** [mbg033/monero-core#66]
i sent 1 xmr out of my GUi wallet (develop Branch) to another address. once i sent the money i switched to History Tab.

When the transaction got mined the GUI crashed:

2016-Oct-05 17:27:19.924347 Found new pool tx: <630bf28284e41b48f7c452b3bbbb7aa9fbe3fd8f933bff14832ae10b0f19ec81>
2016-Oct-05 17:27:20.020631 Found new pool tx: <d40049ba74138583b7f085d76a217ded2e1c9ddc9a06dc8511d22733dec0396d>
2016-Oct-05 17:27:20.105123 Found new pool tx: <b2c38f0fe7eaaa65c986233a91b4cf5aca89b1f1f0bb9ea497746007d603027a>
2016-Oct-05 17:27:20.198016 Found new pool tx: <01d5b0cc6f1f93e682e1373a8dc0513c757815706b3b512d206e6a842ddb02ab>
2016-Oct-05 17:27:20.287003 Found new pool tx: <8fa424e37fe1135397caf0437c529a24a5eb77b8152ac402ce3078da64004051>
2016-Oct-05 17:27:20.392800 Found new pool tx: <152a633a5db26691f9cd08a9456738f1ac61b67cbf738e354c123a220585517d>
2016-Oct-05 17:27:20.484343 Found new pool tx: <c5b6ace2cc4300a4b6e22006a6f400fb73147d3e76a98b13d728ec85d47da3d1>
2016-Oct-05 17:27:20.575713 Found new pool tx: <9a6df0397e6176824e1b5e280fd4fc09928cc52dfbbc7ee319929e1991550c1a>
2016-Oct-05 17:27:20.669680 Found new pool tx: <4999d928bd03f02a7d796bc4fddf9344a54ab1e18d6f11073ac49fa2baf9d57b>
2016-Oct-05 17:27:20.670527 We sent that one
2016-Oct-05 17:27:20.670674 Found new pool tx: <29d5295dc2a0e118bd47ce8195538c6b8ccc093c4d04677eb40a610d2f04998d>
2016-Oct-05 17:27:20.756392 Found new pool tx: <4080273ff826009f782bfbe698b77404c1b8d86c7222c6725b47e3cbcf1e339d>
2016-Oct-05 17:27:20.842935 Found new pool tx: <e33615b3a407f87a3ea08cc55ae4abc3d99668a5197b1058418b58f13a92fdf1>
2016-Oct-05 17:27:20.940772 Refresh done, blocks received: 0, balance: 4.052247660113, unlocked: 2.592247660113
refreshed
qml: >>> wallet refreshed
qml: >>> wallet updated
2016-Oct-05 17:27:31.013726 Received money: 0.060000000000, with tx: <4999d928bd03f02a7d796bc4fddf9344a54ab1e18d6f11073ac49fa2baf9d57b>
moneyReceived
updated
2016-Oct-05 17:27:31.015286 Received money: 0.400000000000, with tx: <4999d928bd03f02a7d796bc4fddf9344a54ab1e18d6f11073ac49fa2baf9d57b>
moneyReceived
updated
2016-Oct-05 17:27:31.016961 Spent money: 0.010000000000, with tx: <4999d928bd03f02a7d796bc4fddf9344a54ab1e18d6f11073ac49fa2baf9d57b>
moneySpent
updated
qrc:///components/HistoryTable.qml:92: ReferenceError: description is not defined
2016-Oct-05 17:27:31.018692 Spent money: 0.500000000000, with tx: <4999d928bd03f02a7d796bc4fddf9344a54ab1e18d6f11073ac49fa2baf9d57b>
moneySpent
updated
qrc:///components/HistoryTable.qml:92: ReferenceError: description is not defined
2016-Oct-05 17:27:31.020434 Spent money: 0.090000000000, with tx: <4999d928bd03f02a7d796bc4fddf9344a54ab1e18d6f11073ac49fa2baf9d57b>
moneySpent
updated
Segmentation fault (core dumped)

**Comment by mbg033** [comment]
Thanks for the report, but yes, development still in progress, it may crash

**Comment by medusadigital** [comment]
fixed-->close
